unpackaged/main/default/objects/GulaError__c/GulaError__c.object-meta.xml
<CustomObject>
    <description>This object stores the Gula App errors.</description>
    <label>Gula Error</label>
    <nameField>
        <displayFormat>GE-{00000000}</displayFormat>
        <label>Gula Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gula Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/GulaError__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Error Code.</description>
    <externalId>true</externalId>
    <inlineHelpText>Error Code.</inlineHelpText>
    <label>Code</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/GulaError__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that caused the error.</description>
    <inlineHelpText>User that caused the error.</inlineHelpText>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipLabel>Gula Errors</relationshipLabel>
    <relationshipName>GulaErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <description>Application users.</description>
    <label>User</label>
    <nameField>
        <displayFormat>U-{000000000}</displayFormat>
        <label>User Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/UtilityGulaClass.cls
/**
 * @author Arcode.
 * @description This class provides developers with different utility methods for Gula App.
 * <p /><p /> 
 */
public class UtilityGulaClass {

    /**
     * This method creates an error record, if needed.
     *
     * @param boolSuccess Indicates if the original transaction was a success
	 * @param intErrorCode Error code.
	 * @param strUserId User Id that caused the error.
     */
	@future
    public static void getErrorSaved(Boolean boolSuccess, Integer intErrorCode, String strUserId) {
        GulaError__c objError = new GulaError__c();

		//Only if indicated, we store the record.
		if(boolSuccess == null || !boolSuccess) {
			objError.Code__c = intErrorCode;
			if(String.isNotBlank(strUserId)) {
				objError.User__c = strUserId;
			}
			insert objError;
		}
    }
}