unpackaged/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <description>Application users.</description>
    <label>User</label>
    <nameField>
        <displayFormat>U-{000000000}</displayFormat>
        <label>User Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <description>Currency of the price range of the provider.</description>
    <inlineHelpText>Currency of the price range of the provider.</inlineHelpText>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>BTC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/UserGulaWrapperClass.cls
/**
 * @author Arcode.
 * @description This class serves as a wrapper for User data.
 * <p /><p /> 
 */
global virtual class UserGulaWrapperClass extends AuthenticationGulaWrapperClass {

	//Public variables.
	@AuraEnabled
	public Boolean boolAlreadyExists {get; set;}
	@AuraEnabled
	public Boolean boolActiveGPSTracking {get; set;}
	@AuraEnabled
	public Boolean boolAcceptedTermsAndConditions {get; set;}
	@AuraEnabled
	public Double dblMaximumPrice {get; set;}
	@AuraEnabled
	public Double dblMinimumPrice {get; set;}
	@AuraEnabled
	public String strCurrency {get; set;}
	@AuraEnabled
	public String strPublicName {get; set;}
	@AuraEnabled
	public List<String> lstCategories {get; set;}
	@AuraEnabled
	public List<Object> lstPulls {get; set;}
	@AuraEnabled
	public List<String> lstCurrencies {
		get {
			List<String> lstValues = new List<String>();
			for(Schema.PicklistEntry objPicklistValue : User__c.Currency__c.getDescribe().getPicklistValues()) {
				lstValues.add(objPicklistValue.getLabel());
			}     
			return lstValues;
		}
	}
}