unpackaged/main/default/objects/Credential__mdt/Credential__mdt.object-meta.xml
<CustomObject>
    <description>Endpoint Credentials.</description>
    <label>Credential</label>
    <pluralLabel>Credentials</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Credential__mdt/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <description>Client Id.</description>
    <inlineHelpText>Client Id.</inlineHelpText>
    <label>Client Id</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Credential__mdt/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <description>Client Secret.</description>
    <inlineHelpText>Client Secret.</inlineHelpText>
    <label>Client Secret</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Endpoint__mdt/Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>Integration Endpoints.</description>
    <label>Endpoint</label>
    <pluralLabel>Endpoints</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Endpoint__mdt/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <description>Endpoint credentials.</description>
    <inlineHelpText>Endpoint credentials.</inlineHelpText>
    <label>Credential</label>
    <referenceTo>Credential__mdt</referenceTo>
    <relationshipLabel>Endpoints</relationshipLabel>
    <relationshipName>Endpoints</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/Endpoint__mdt/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <description>Endpoint environment.</description>
    <inlineHelpText>Endpoint environment.</inlineHelpText>
    <label>Environment</label>
    <referenceTo>Environment__mdt</referenceTo>
    <relationshipLabel>Endpoints</relationshipLabel>
    <relationshipName>Endpoints</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

unpackaged/main/default/objects/Endpoint__mdt/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <description>This field stores custom headers on a pair key-value format, so they can be included on the request.</description>
    <inlineHelpText>This field stores custom headers on a pair key-value format, so they can be included on the request.</inlineHelpText>
    <label>Headers</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Endpoint__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>HTTP Method.</description>
    <inlineHelpText>HTTP Method.</inlineHelpText>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>SET</fullName>
                <isActive>false</isActive>
                <label>SET</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Endpoint__mdt/fields/RedirectURI__c.field-meta.xml
<CustomField>
    <fullName>RedirectURI__c</fullName>
    <description>Redirect URI.</description>
    <inlineHelpText>Redirect URI.</inlineHelpText>
    <label>Redirect URI</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Endpoint__mdt/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Endpoint URL.</description>
    <inlineHelpText>Endpoint URL.</inlineHelpText>
    <label>URL</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Environment__mdt/Environment__mdt.object-meta.xml
<CustomObject>
    <description>Environments for Endpoints.</description>
    <label>Environment</label>
    <pluralLabel>Environments</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Environment__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the record is active.</description>
    <inlineHelpText>Indicates if the record is active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Environment__mdt/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Environment Id.</description>
    <inlineHelpText>Environment Id.</inlineHelpText>
    <label>Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>This object stores the Callout transactions, DML errors and Exceptions occurred in the applications.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transaction__c/fields/BodyBlob__c.field-meta.xml
<CustomField>
    <fullName>BodyBlob__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates if the request body was a blob.</description>
    <inlineHelpText>This field indicates if the request body was a blob.</inlineHelpText>
    <label>Body Blob</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/CorrelationId__c.field-meta.xml
<CustomField>
    <fullName>CorrelationId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is used to correlate logs stored in SFDC with External systems.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field is used to correlate logs stored in SFDC with External systems.</inlineHelpText>
    <label>Correlation Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint related to the Callout request.</description>
    <inlineHelpText>Endpoint related to the Callout request.</inlineHelpText>
    <label>Endpoint</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <description>Serialized headers.</description>
    <inlineHelpText>Serialized headers.</inlineHelpText>
    <label>Headers</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/IsEncrypted__c.field-meta.xml
<CustomField>
    <fullName>IsEncrypted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates if the record is encrypted or not.</description>
    <inlineHelpText>This field indicates if the record is encrypted or not.</inlineHelpText>
    <label>Is Encrypted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Error message.</description>
    <inlineHelpText>Error message.</inlineHelpText>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>HTTP Method used for callout.</description>
    <inlineHelpText>HTTP Method used for callout.</inlineHelpText>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/RelatedTransaction__c.field-meta.xml
<CustomField>
    <fullName>RelatedTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains a Parent transaction that originated the current one.</description>
    <inlineHelpText>This field contains a Parent transaction that originated the current one.</inlineHelpText>
    <label>Related Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Exceptions</relationshipLabel>
    <relationshipName>RelatedTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>Request payload.</description>
    <inlineHelpText>Request payload.</inlineHelpText>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Response payload.</description>
    <inlineHelpText>Response payload.</inlineHelpText>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/ResponseBodyBlob__c.field-meta.xml
<CustomField>
    <fullName>ResponseBodyBlob__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field indicates if the response body was a blob.</description>
    <inlineHelpText>This field indicates if the response body was a blob.</inlineHelpText>
    <label>Response Body Blob</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseCode__c</fullName>
    <description>Response code of the transaction.</description>
    <inlineHelpText>Response code of the transaction.</inlineHelpText>
    <label>Response Code</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/ResponseHeaders__c.field-meta.xml
<CustomField>
    <fullName>ResponseHeaders__c</fullName>
    <description>Response HTTP Headers.</description>
    <inlineHelpText>Response HTTP Headers.</inlineHelpText>
    <label>Response Headers</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Stack Trace related to the exception.</description>
    <inlineHelpText>Stack Trace related to the exception.</inlineHelpText>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Transaction__c/recordTypes/Callout.recordType-meta.xml
<RecordType>
    <fullName>Callout</fullName>
    <active>true</active>
    <description>Callout record type.</description>
    <label>Callout</label>
</RecordType>

unpackaged/main/default/objects/Transaction__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <description>Exception record type.</description>
    <label>Exception</label>
</RecordType>

unpackaged/main/default/classes/TransactionClass.cls
/**
 * @author Arcode.
 * @description This class helps developers to log transactions (callouts, DMLs and Exceptions).
 * <p /><p /> 
 */
global without sharing class TransactionClass {

	//Public variables.
	public static final Boolean BOOLEAN_ENCRYPT_ALL_DATA = UtilitiesClass.getEnvironmentConfiguration().EncryptTransactionFields__c;
	public static final String STRING_LOGGING_LEVEL = UtilitiesClass.getEnvironmentConfiguration().LoggingLevel__c;
	public static final Id ID_RECORD_TYPE_CALLOUT = Schema.SObjectType.Transaction__c.getRecordTypeInfosByDeveloperName().get('Callout').getRecordTypeId();
	public static final Id ID_RECORD_TYPE_EXCEPTION = Schema.SObjectType.Transaction__c.getRecordTypeInfosByDeveloperName().get('Exception').getRecordTypeId();
    public static String strCode;

	/**
     * This method executes a callout.
     * 
     * @param objData Request data.
     * @return TransactionWrapperClass.
     */
    @AuraEnabled(cacheable = false)
	public static TransactionWrapperClass callout(TransactionWrapperClass objData) {

		//First we check if we received a request.
		if(objData != null) {

			//Now we get the endpoint.
			objData = getEndpoint(objData);

			//Now get replace the path variables.
			objData = getPathVariablesReplaced(objData);

			//Now we execute the callout.
			if(objData.boolExecuteInFuture == null || !objData.boolExecuteInFuture) {
				objData = executeCallout(objData);
			} else {
				executeCalloutInFuture(JSON.serialize(objData, true));
			}
		}

		//Finally, we return the result.
		return objData;
	}

	/**
     * This method returns the endpoint data.
     * 
     * @param objData Request data.
     * @return TransactionWrapperClass.
     */
	@AuraEnabled(cacheable = false)
	public static TransactionWrapperClass getEndpoint(TransactionWrapperClass objData) {
		String strLabel = objData.strLabel;
		String strEnvironmentId = UserInfo.getOrganizationId();
		String strEnvironmentId15Digits = strEnvironmentId.substring(0, 15);
		Map<String, String> mapHeaders;

		//Now we query the endpoint.
		if(objData != null && String.isNotBlank(strLabel)) {
			
			for(Endpoint__mdt objEndpoint : [SELECT Credential__r.ClientId__c, Credential__r.ClientSecret__c, URL__c, Method__c, RedirectURI__c, Headers__c FROM Endpoint__mdt WHERE 
					Label = :strLabel AND Active__c = TRUE AND (Environment__r.Id__c = :strEnvironmentId OR Environment__r.Id__c = :strEnvironmentId15Digits) AND 
					Environment__r.Active__c = TRUE LIMIT 1]) {

				//We set the credentials, if any.
				if(objEndpoint.Credential__r != null) {
					objData.strClientId = objEndpoint.Credential__r.ClientId__c;
					objData.strClientSecret = objEndpoint.Credential__r.ClientSecret__c;
				}
				
				//Now we set the rest of the properties.
				objData.strEndpoint = objEndpoint.URL__c;
				objData.strMethod = objEndpoint.Method__c;
				objData.strRedirectURI = objEndpoint.RedirectURI__c;

				//Now we check any possible custom headers, stores on the Endpoint record.
				if(String.isNotBlank(objEndpoint.Headers__c)) {
					if(objData.mapHeaders == null) {
						objData.mapHeaders = new Map<String, String>();
					}
					mapHeaders = (Map<String, String>) JSON.deserialize(objEndpoint.Headers__c, Map<String, String>.class);
					for(String strKey : mapHeaders.keySet()) {
						objData.mapHeaders.put(strKey, mapHeaders.get(strKey));
					}
				}
			}
		}

		return objData;
	}

	/**
     * This method replaces the path variables in the URL.
     * 
     * @param objData Request data.
     * @return TransactionWrapperClass.
     */
	@AuraEnabled(cacheable = false)
	public static TransactionWrapperClass getPathVariablesReplaced(TransactionWrapperClass objData) {
		String strValue;

		//If we require to replace the path variables.
		if(objData != null && objData.mapPathVariables != null && String.isNotBlank(objData.strEndpoint)) {
			for(String strPathVariable : objData.mapPathVariables.keySet()) {
				
				//If we have an endpoint.
				objData.strEndpoint = objData.strEndpoint.replace('{{' + strPathVariable + '}}', objData.mapPathVariables.get(strPathVariable));
			}
		}

		//If we require to replace variables on the headers [Client Id, Client Secret]
		if(objData.mapHeaders != null) {
			for(String strKey : objData.mapHeaders.keySet()) {
				strValue = objData.mapHeaders.get(strKey);

				//We look for client id.
				if(strValue.contains('{{ClientId}}')) {
					strValue = strValue.replace('{{ClientId}}', objData.strClientId);
				}

				//We look for client secret.
				if(strValue.contains('{{ClientSecret}}')) {
					strValue = strValue.replace('{{ClientSecret}}', objData.strClientSecret);
				}

				//We save the changes.
				objData.mapHeaders.put(strKey, strValue);
			}
		}
		return objData;
	}

	/**
     * This method executes a callout based on the provided data, in a future method.
     * 
     * @param strSerializedData Request data.
     */
	@future(callout = true)
	public static void executeCalloutInFuture(String strSerializedData) {
		if(String.isNotBlank(strSerializedData)) {
			executeCallout((TransactionWrapperClass) JSON.deserialize(strSerializedData, TransactionWrapperClass.class));
		}
	}

	/**
     * This method executes a callout based on the provided data.
     * 
     * @param objData Request data.
     * @return TransactionWrapperClass.
     */
	@AuraEnabled(cacheable = false)
	public static TransactionWrapperClass executeCallout(TransactionWrapperClass objData) {
        Http objHttp = new Http();
        HttpRequest objHttpRequest = new HttpRequest();
        HttpResponse objResponse;
		Transaction__c objTransaction = new Transaction__c();
		TransactionWrapperClass objResult = new TransactionWrapperClass();

		//We use Try-Catch-Finally.
		try {
			objResult.boolHasException = false;
			objTransaction.RecordTypeId = ID_RECORD_TYPE_CALLOUT;

			//If we have the required data.
			if(objData != null) {
				
				//If we have headers to add.
				if(objData.mapHeaders != null) {
					for(String strKey : objData.mapHeaders.keySet()) {
					
						//If we have an endpoint.
						objHttpRequest.setHeader(strKey, objData.mapHeaders.get(strKey));
					}
					objTransaction.Headers__c = getStringEncrypted(JSON.serialize(objData.mapHeaders, true));
				}

				//If the label is 'GitHub Get User Data'.
				if(objData.strLabel == 'GitHub Get User Data') {
				objData.strBody = ('client_id=' + objData.strClientId + '&client_secret=' + objData.strClientSecret + '&code=' + objData.strCode + '&redirect_uri=' 
				+ objData.strRedirectURI);
				} else if(objData.strLabel == 'GitHub Create Pull Request') {
					String payload = JSON.serialize(new Map<String,Object>{
						'title' => 'TestRichard',
						'body' => 'new Pull request!',
						'head' => 'TestRichard',
						'base' => 'master'
					});
					objData.strBody = payload;

				//If the label is 'GitHub Create Commit'.	
				} else if(objData.strLabel == 'GitHub Create Commit') {
					Blob value = Blob.valueOf('HolaaaaMonse');
					String content = EncodingUtil.base64Encode(value);
					String payload = JSON.serialize(new Map<String,Object>{
						'message' => 'Ready',
						'content' => content,
						'name' => 'notes',
						'sha' => '242aff811a42af61616cd2c97d99f35363659364',
						'branch' => 'master'
					});
					objData.strBody = payload;
				}

				//If we have a body.
				if(String.isNotBlank(objData.strBody)) {
					objHttpRequest.setBody(objData.strBody);
					objTransaction.Request__c = getStringEncrypted(objData.strBody);
					objTransaction.BodyBlob__c = false;
				} else if(objData.objBody != null) {
					objHttpRequest.setBodyAsBlob(objData.objBody);
					objTransaction.Request__c = getStringEncrypted(objData.objBody.toString());
					objTransaction.BodyBlob__c = true;
				}

				//If we have a method.
				if(String.isNotBlank(objData.strMethod)) {
					objData.strMethod = objData.strMethod.toUpperCase();
					objHttpRequest.setMethod(objData.strMethod);
					objTransaction.Method__c = objData.strMethod;
				}

				//If we have an endpoint.
				if(String.isNotBlank(objData.strEndpoint)) {
					objHttpRequest.setEndpoint(objData.strEndpoint);
					objTransaction.Endpoint__c = getStringEncrypted(objData.strEndpoint);
				}

				//Now we execute the callout.
				objResponse = objHttp.send(objHttpRequest);

				//Now we extract the response.
				objResult.intStatusCode = objResponse.getStatusCode();
				objResult.strBody = objResponse.getBody();
				objResult.objBody = objResponse.getBodyAsBlob();
				objResult.mapHeaders = new Map<String, String>();
				for(String strHeader : objResponse.getHeaderKeys()) {
					objResult.mapHeaders.put(strHeader, objResponse.getHeader(strHeader));
				}

				//Now we set the Transaction updates.
				objTransaction.IsEncrypted__c = BOOLEAN_ENCRYPT_ALL_DATA;
				objTransaction.ResponseCode__c = objResult.intStatusCode;
				objTransaction.ResponseHeaders__c = getStringEncrypted(JSON.serialize(objResult.mapHeaders, true));
				if(String.isNotBlank(objResult.strBody)) {
					objTransaction.Response__c = getStringEncrypted(objResult.strBody);
					objTransaction.ResponseBodyBlob__c = false;
				} else {
					objTransaction.Response__c = getStringEncrypted(objResult.objBody.toString());
					objTransaction.ResponseBodyBlob__c = true;
				}
			}
		} catch(Exception objException) {
			
			//Now we process the exception.
			objResult.boolHasException = true;
			objResult.objException = objException;
			objTransaction.RelatedTransaction__r = getExceptionProcessed(objException, false);
		} finally {

			//Now we update the Transaction (Callout) record.
			if(STRING_LOGGING_LEVEL == 'All' || objTransaction.ResponseCode__c < 200 || objTransaction.ResponseCode__c > 299) {
				objResult.strCorrelationId = getTransactionRecordEnqueued(objTransaction);
			}
		}

		//Now we return the result.
		return objResult;
	}

    /**
     * This method enqueues the transaction record upsertion.
	 * 
	 * @param objTransaction Transaction record to be saved.
	 * @return String.
     */
    public static String getTransactionRecordEnqueued(Transaction__c objTransaction) {
		String strCorrelationId;
		if(objTransaction != null) {

			//We generate the GUID and send it back to the caller, if the transaction is a Callout.
			if(objTransaction.RecordTypeId == ID_RECORD_TYPE_CALLOUT) {
				strCorrelationId = UtilitiesClass.getGUID();
				objTransaction.CorrelationId__c = strCorrelationId;
			}

			//Now we enqueue the job.
			System.enqueueJob(new TransactionQueueableClass(objTransaction));
		}
		return strCorrelationId;
	}

    /**
     * This method creates the transaction record.
	 * 
	 * @param objTransaction Transaction record to be saved.
	 * @return Transaction__c.
     */
    public static Transaction__c getTransactionRecordUpserted(Transaction__c objTransaction) {
		Integer intLimit = 131072;
		Attachment objAttachment;
		Transaction__c objChildTransaction;
		UtilitiesWrapperClass objRequest = new UtilitiesWrapperClass();
		List<Attachment> lstAttachments = new List<Attachment>();

		//First we make sure we received something to insert.
		if(objTransaction != null) {

			//First we remove child records, if any.
			if(objTransaction.RelatedTransaction__r != null) {
				objChildTransaction = objTransaction.RelatedTransaction__r;
				objTransaction.RelatedTransaction__r = null;
			}

			//Now we check if any of the text areas are not enough (space), in which case we store the data as Attachments.
			if(String.isNotBlank(objTransaction.Endpoint__c) && objTransaction.Endpoint__c.length() > intLimit) {
				lstAttachments.add(getAttachmentPrepared(!objTransaction.IsEncrypted__c, 'Endpoint__c', objTransaction.Endpoint__c));
			}
			if(String.isNotBlank(objTransaction.Headers__c) && objTransaction.Headers__c.length() > intLimit) {
				lstAttachments.add(getAttachmentPrepared(!objTransaction.IsEncrypted__c, 'Headers__c', objTransaction.Headers__c));
			}
			if(String.isNotBlank(objTransaction.ResponseHeaders__c) && objTransaction.ResponseHeaders__c.length() > intLimit) {
				lstAttachments.add(getAttachmentPrepared(!objTransaction.IsEncrypted__c, 'ResponseHeaders__c', objTransaction.ResponseHeaders__c));
			}
			if(String.isNotBlank(objTransaction.Message__c) && objTransaction.Message__c.length() > intLimit) {
				lstAttachments.add(getAttachmentPrepared(!objTransaction.IsEncrypted__c, 'Message__c', objTransaction.Message__c));
			}
			if(String.isNotBlank(objTransaction.Request__c) && objTransaction.Request__c.length() > intLimit) {
				lstAttachments.add(getAttachmentPrepared(!objTransaction.IsEncrypted__c, 'Request__c', objTransaction.Request__c));
			}
			if(String.isNotBlank(objTransaction.Response__c) && objTransaction.Response__c.length() > intLimit) {
				lstAttachments.add(getAttachmentPrepared(!objTransaction.IsEncrypted__c, 'Response__c', objTransaction.Response__c));
			}
			if(String.isNotBlank(objTransaction.StackTrace__c) && objTransaction.StackTrace__c.length() > intLimit) {
				lstAttachments.add(getAttachmentPrepared(!objTransaction.IsEncrypted__c, 'StackTrace__c', objTransaction.StackTrace__c));
			}

			//Now we insert the transaction object.
			if(String.isNotBlank(objTransaction.CorrelationId__c)) {
				upsert objTransaction CorrelationId__c;
			} else if(objTransaction.Id != null) {
				update objTransaction;
			} else {

				//If the transaction is a Callout.
				if(objTransaction.RecordTypeId == ID_RECORD_TYPE_CALLOUT) {
					objTransaction.CorrelationId__c = UtilitiesClass.getGUID();
				}
				
				//Now we insert the record.
				insert objTransaction;
			}

			//If we have attachments to insert, we populate the parent ids.
			if(!lstAttachments.isEmpty()) {
				for(Attachment objAttachmentToInsert : lstAttachments) {
					objAttachmentToInsert.ParentId = objTransaction.Id;
				}
				insert lstAttachments;
			}

			//Now, we check if we received a related transaction, and we process it.
			if(objChildTransaction != null) {
				objChildTransaction.RelatedTransaction__c = objTransaction.Id;
				getTransactionRecordUpserted(objChildTransaction);
			}
		}
		return objTransaction;
    }

    /**
     * This method prepares an Attachment record with a predefined structure and encryption.
	 * 
	 * @param boolEncrypt Request data.
	 * @param strName File Name.
	 * @param strBody Attachment body.
     * @return Attachment.
     */
    public static Attachment getAttachmentPrepared(Boolean boolEncrypt, String strName, String strBody) {
		Attachment objAttachment = new Attachment();
		UtilitiesWrapperClass objRequest = new UtilitiesWrapperClass();

		//We check if we need to encrypt the content.
		if(boolEncrypt) {
			objRequest.boolEncrypt = true;
			objRequest.boolEnvironmentSpecific = true;
			objRequest.strText = strBody;
			objAttachment.Body = Blob.valueOf(UtilitiesClass.getStringEncryptedDecrypted(objRequest));
		} else {
			objAttachment.Body = Blob.valueOf(strBody);
		}

		//We set the name and return the attachment structure.
		objAttachment.Name = strName + '.arcode';
		return objAttachment;
    }

    /**
     * This method extracts the exception data and then throws the exception back to the caller.
	 * 
	 * @param objException Exception to be processed.
	 * @return Transaction__c.
     */
    public static Transaction__c getExceptionProcessed(Exception objException, Boolean boolImmediateInsert) {
		Transaction__c objTransaction = new Transaction__c();

		//First we check if we received the exception.
		if(objException != null) {
			objTransaction.RecordTypeId = ID_RECORD_TYPE_EXCEPTION;
			objTransaction.Message__c = objException.getMessage();
			objTransaction.StackTrace__c = objException.getStackTraceString();

			//If we want to insert the transaction.
			if(boolImmediateInsert != null && boolImmediateInsert) {
				getTransactionRecordEnqueued(objTransaction);
			}
		}
		return objTransaction;
	}

    /**
     * This method encrypts a string, if the global configuration requests it.
	 * 
	 * @param strText Text to be encrypted.
     * @return String.
     */
    public static String getStringEncrypted(String strText) {
		String strResult = strText;
		UtilitiesWrapperClass objRequest = new UtilitiesWrapperClass();
		//We check if we need to encrypt the content.
		if(BOOLEAN_ENCRYPT_ALL_DATA) {
			objRequest.boolEncrypt = true;
			objRequest.boolEnvironmentSpecific = true;
			objRequest.strText = strText;
			strResult = UtilitiesClass.getStringEncryptedDecrypted(objRequest);
		}
		return strResult;
    }
}